Repository Jiii-Eun/taskify, pull requests merged in 2025-09, with the labels that each got.

#17 [feature/login] login 페이지 UI 및 기능 구현
  src/app/login/page.tsx
  src/components/form/Field.tsx
  src/components/form/Input.tsx
  src/components/form/Select.tsx
Labels: ✨Feature

#33 [Feature/dashboardedit] 대시보드 수정 페이지 UI 구현
  src/app/dashboard/[id]/edit/page.tsx
  src/components/chip/Chip.tsx
Labels: ✨Feature, 🎨UI

#34 [Feature] datePicker 설치, TagInput, ImgUpLoad 구현
  components.json
  package-lock.json
  package.json
  src/app/dashboard/[id]/page.tsx
  src/app/dashboard/components/BoardsModal.tsx
  src/app/dashboard/components/CreateModal.tsx
  src/app/dashboard/components/ModifyModal.tsx
  src/components/form/DatePicker.tsx
  src/components/form/ImgUpload.tsx
  src/components/form/Select.tsx
  src/components/form/TagInput.tsx
Labels: ✨Feature, 🛠️Fix

#35 [sidebar] 대시보드 클릭시 이동 / [home] UI 구현 및 링크연결
  public/images/img-logo-large-white.svg
  public/images/img-logo-small-white.svg
  src/app/dashboard/[id]/page.tsx
  src/app/dashboard/layout.tsx
  src/app/dashboard/page.tsx
  src/app/layout.tsx
  src/app/mydashboard/layout.tsx
  src/app/page.tsx
  src/components/card/Card.tsx
  src/components/home/flow
  src/components/layout/Logo.tsx
  src/components/layout/Pagination.tsx
  src/components/layout/PaginationButton.tsx
  src/components/layout/dashboard/DashboardLayout.tsx
  src/components/layout/dashboard/Navbar/MemberList.tsx
  src/components/layout/dashboard/Navbar/index.tsx
  src/components/layout/dashboard/Sidebar/DashboardList.tsx
  src/components/layout/dashboard/Sidebar/flow
  src/components/layout/dashboard/Sidebar/index.tsx
  src/components/layout/home/Footer.tsx
  src/components/layout/home/Header.tsx
  src/components/layout/home/TestLogin.tsx
  src/components/layout/home/flow
Labels: ✨Feature, 🎨UI

#37 [feature/dashboardid] 대시보드 상세 페이지 반응형 디자인
  public/images/img-profile-sample.svg
  src/app/dashboard/[id]/edit/page.tsx
  src/app/dashboard/[id]/page.tsx
  src/components/card/Card.tsx
  src/components/column/Column.tsx
  src/components/layout/dashboard/Sidebar/index.tsx
Labels: 🎨UI

#45 [notfound] 반응형UI / sidebar, navbar UI수정
  public/video/Loading_Animation.webm
  public/video/Puzzle_Loader.webm
  src/app/Loading.tsx
  src/app/dashboard/page.tsx
  src/app/not-found.tsx
  src/app/page.tsx
  src/components/layout/Logo.tsx
  src/components/layout/Pagination.tsx
  src/components/layout/dashboard/DashboardLayout.tsx
  src/components/layout/dashboard/Navbar/index.tsx
  src/components/layout/dashboard/Sidebar/DashboardList.tsx
  src/components/layout/dashboard/Sidebar/index.tsx
  src/styles/globals.css
Labels: 🎨UI

#46 [Feature] 컬럼 모달 구현/ api 연결
  src/app/dashboard/components/CreateColumnModal.tsx
  src/app/dashboard/components/DeleteColumnModal.tsx
  src/app/dashboard/components/ManageColumnModal.tsx
Labels: ✨Feature

#52 [inviteModal] 대시보드 생성 연결, 초대하기 모달 UI 및 구현 / 모달 연결
  eslint.config.mjs
  package-lock.json
  package.json
  src/app/dashboard/[id]/edit/page.tsx
  src/components/CreateDashboardModal.tsx
  src/components/home/Home.tsx
  src/components/layout/LoggedInLayout.tsx
  src/components/layout/dashboard/Navbar/NavButton.tsx
  src/components/layout/dashboard/Navbar/flow
  src/components/layout/dashboard/Navbar/index.tsx
  src/components/layout/dashboard/Sidebar/flow
  src/components/layout/home/TestLogin.tsx
Labels: ✨Feature, 🎨UI

#57 [Feature/card modal] api 아이디 연결
  src/app/dashboard/[id]/page copy.tsx
  src/app/dashboard/[id]/page.tsx
  src/app/dashboard/components/cardModal/Comment.tsx
  src/app/dashboard/components/cardModal/CreateCardModal.tsx
  src/app/dashboard/components/cardModal/DetailCardModal.tsx
  src/app/dashboard/components/cardModal/ModifyCardModal.tsx
  src/app/dashboard/components/columModal/CreateColumnModal.tsx
  src/components/card/Card.tsx
  src/components/form/TagInput.tsx
  src/features/columns/store.ts
Labels: 🛠️Fix

#59 [feature/dashboardid] 대시보드 상세 페이지에서 카드 생성 후 새로고침 시 카드 삭제되는 오류 해결
  src/app/dashboard/[id]/page.tsx
  src/components/card/Card.tsx
  src/components/column/Column.tsx
  src/components/common/dashboard/Sidebar/index.tsx
  src/components/form/ImgUpload.tsx
  src/components/layout/DashboardLayout.tsx
  src/components/modal/cardModal/CreateCardModal.tsx
Labels: ✨Feature, 🛠️Fix

#86 [Feature/fix card modal] 모달 포탈로 만들기, 카드 제목 오류 수정
  src/app/layout.tsx
  src/app/not-found.tsx
  src/components/card/Card.tsx
  src/components/modal/Modal.tsx
  src/components/modal/cardModal/DetailCardModal.tsx
Labels: 🛠️Fix, ♻️Refactor

#90 [Feature/fix card modal] zustand사용 제거, 카드수정, 생성 모달 병합
  src/app/(protected)/dashboard/[id]/page.tsx
  src/components/card/Card.tsx
  src/components/column/Column.tsx
  src/components/form/DatePicker.tsx
  src/components/modal/cardModal/CardModal.tsx
  src/components/modal/cardModal/Comment.tsx
  src/components/modal/cardModal/CreateCardModal.tsx
  src/components/modal/cardModal/DetailCardModal.tsx
  src/components/modal/cardModal/ModifyCardModal.tsx
  src/components/modal/columnModal/CreateColumnModal.tsx
  src/components/modal/columnModal/DeleteColumnModal.tsx
  src/components/modal/refactor
  src/features/dashboard/types.ts
Labels: 🛠️Fix, ♻️Refactor
